### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Priyanshu348** [F4stZ4p/HLavalink#1]
It shows app exited

**Comment by Tenpi** [comment]
It's just crashing for me.

**Comment by QuirijnLangedijk** [comment]
Doesnt look like it's fixed, app is stuck on 'Startin lavalink...'
![image](https://user-images.githubusercontent.com/31623496/78882786-dfe10c00-7a58-11ea-8d2d-a10aecbe93dd.png)

**Comment by F4stZ4p** [comment]
Now it works, closing this
