### ISSUE TITLE
Unexpected response : 503

### ISSUE THREAD

**Issue by JarodStreck** [F4stZ4p/HLavalink#2]
Hi, it looks like the Lavalink server isn't starting when deployed.

![error](https://user-images.githubusercontent.com/38767523/80859923-8b4e3c80-8c64-11ea-88bc-c0fc41ecbf47.PNG)
![error2](https://user-images.githubusercontent.com/38767523/80859924-8e492d00-8c64-11ea-8d88-af3e7e5fbf45.PNG)

When using the heroku console i can't find the Laravel.jar , maybe it doesn't download it well ? 

i'm using discord.js with erela.js

**Comment by F4stZ4p** [comment]
It works now

**Comment by gamer23232323** [comment]
> It works now

no, its no works
