### ISSUE TITLE
not sure if this is an issue, but it keeps reconnecting to the node.

### ISSUE THREAD

**Issue by ender** [F4stZ4p/HLavalink#3]
again, im not sure if this is an issue, or something im doing wrong, but i am able to connect to the node, and every now and then it reconnects, and after 5 reconnects it says **Node error: Unable to connect after 5**

**Comment by kakarot-dev** [comment]
Yes it is an isue

**Comment by kakarot-dev** [comment]
Thats bcause ths lavalink is old
